export const FORM_INPUT_NAMES = {
  TRELLO_LABEL_SELECTOR: "TrelloLabelSelector",
  SHORT_TEXT: "EditText",
  LONG_TEXT: "LongText",
  EMAIL: "Email",
  NUMBER: "Number",
  WEBSITE: "Website",
  PHONE: "Phone",
  BUTTON: "Button",
  ATTACHMENT: "Attachment",
  DATE_PICKER_ITEM: "Date",
  DATE_TIME_PICKER_ITEM: "DateTime",
  TIME_PICKER: "Time",
  RADIO_BUTTON: "RadioButton",
  SELECT_BOX: "SelectBox",
  CAPTCHA: "Captcha",
  HORIZONTAL_LINE: "HorizontalLine",
  PARAGRAPH: "Paragraph",
  TITLE: "Title",
  RATING_ITEM: "Rating",
  CHECKBOX: "Checkbox",
  MULTISELECTBOX: "MultiSelectBox",
  RICH_TEXT_INPUT: "RichTextInput",
  BOOLEAN: "Boolean"
};