const SUBDOMAIN_BLACKLIST = ["playground", "console", "hippo", "admin"]
const PAGE_SLUG_BLACKLIST = [
  "forms",
  "form",
  "page",
  "signin",
  "signup",
  "forgot"
]
const APP_SLUG_BLACKLIST = [
  "hippo",
  "trello",
  "hipporello",
  "onboarding"
]
const LATEST_APP_SCHEMA_VERSION = 5;
const VARIABLE_TYPES = ["string", "double", "long", "boolean", "attachment", "date", "datetime", "time"]
const RESOLVE_TYPES = {
  RESOLVE_LIST_BY_HIPPO_ID: "RESOLVE_LIST_BY_HIPPO_ID",
  RESOLVE_LABEL_BY_HIPPO_ID: "RESOLVE_LABEL_BY_HIPPO_ID",
  RESOLVE_MEMBER_BY_TRELLO_ID: "RESOLVE_MEMBER_BY_TRELLO_ID",
  RESOLVE_USER_BY_USER_ID: "RESOLVE_USER_BY_USER_ID",
  RESOLVE_BOARD_BY_TRELLO_BOARD_ID: "RESOLVE_BOARD_BY_TRELLO_BOARD_ID",
  RESOLVE_CARD_BY_CARD_ID: "RESOLVE_CARD_BY_CARD_ID",
  RESOLVE_FIELD_DEFINITION_BY_ID: "RESOLVE_FIELD_DEFINITION_BY_ID",
  RESOLVE_CHECKLIST_BY_HIPPO_ID: "RESOLVE_CHECKLIST_BY_HIPPO_ID",
}
const OPERATORS = [
  "equals",
  "notequals",
  "contains",
  "notcontains",
  "startswith",
  "notstartswith",
  "endswith",
  "notendswith",
  "lessthan",
  "lessthanequals",
  "greaterthan",
  "greaterthanequals",
  "in",
  "allin",
  "anyin",
  "notin",
  "empty",
  "notempty",
  "has",
  "hasall",
  "hasany",
  "hasnone",
  "doesnthave",
]
const COMPONENT_TYPES = [
  "header",
  "paragraph",
  "list",
  "icon",
  "appList",
  "formList",
  "sidebar",
  "hyperlink",
  "image",
  "video",
  "hippoFields",
  "appVariables",
  "label",
  "button",
  "TrelloCardSharing",
  "trelloChecklist",
  "table",
  "date",
  "dropdown",
  "row",
  "Image",
  "AppVariables",
  "Header",
  "horizontalline",
  "html",
  "dropdownItem",
  "attachmentList",
  "menuItem",
  "cardMenuItem",
  "tableColumn",
  "menu",
  "HippoFields",
  "Conversation",
  "column",
  "columns",
  "userManagement",
  "shareButton",
  "customFields",
  "trelloActivities",
  "accordion",
  "accordionItem",
  "accordionItemBody",
  "accordionItemHeader"
]
const FILE_MIME_MAPPING = {
  pdf: "application/pdf",
  doc: "application/msword",
  docx: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  xls: "application/vnd.ms-excel",
  xlsx: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  csv: "text/csv",
  txt: "text/plain",
  rtf: "application/rtf",
  html: "text/html",
  zip: "application/zip",
  mp3: "audio/mpeg",
  wma: "audio/x-ms-wma",
  mpg: "video/mpeg",
  flv: "video/x-flv",
  avi: "video/x-msvideo",
  jpg: "image/jpeg",
  jpeg: "image/jpeg",
  png: "image/png",
  gif: "image/gif"
}

export {
  VARIABLE_TYPES,
  RESOLVE_TYPES,
  OPERATORS,
  LATEST_APP_SCHEMA_VERSION,
  SUBDOMAIN_BLACKLIST,
  PAGE_SLUG_BLACKLIST,
  APP_SLUG_BLACKLIST,
  COMPONENT_TYPES,
  FILE_MIME_MAPPING
};
